# Generated by Django 2.2.17 on 2021-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beutils_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='emoji_u',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='region',
            name='emoji',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='region',
            name='emoji_u',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
