# Generated by Django 3.1.1 on 2021-02-17 11:13


# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ GENERAL IMPORTS                                                                    │
# └────────────────────────────────────────────────────────────────────────────────────┘

import os

# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ DJANGO IMPORTS                                                                     │
# └────────────────────────────────────────────────────────────────────────────────────┘

from django.db import migrations


# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ BEUTIL IMPORTS                                                                     │
# └────────────────────────────────────────────────────────────────────────────────────┘

from beutils.tools import read_json, slugify


# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ CREATE CRYPTO CURRENCIES                                                           │
# └────────────────────────────────────────────────────────────────────────────────────┘


def create_crypto_currencies(apps, schema_editor):
    """ Creates Currency objects of type crypto from currency fixtures """

    # Get Currency model
    Currency = apps.get_model("beutils_currency", "Currency")

    # Define fixture directory
    file_directory = "beutils/currency/fixtures/"

    # Define currency file name
    file_name = "crypto.json"

    # Read currency fixture file
    currencies = read_json(os.path.join(file_directory, file_name))

    # Return if file not found
    if not currencies:
        return

    # Get list of existing crypto codes
    existing_codes = Currency.objects.filter(kind="crypto").values_list(
        "code", flat=True
    )

    # Bulk create currencies
    Currency.objects.bulk_create(
        [
            Currency(
                name=currency["name"],
                slug=slugify(currency["name"]),
                code=currency["code"],
                symbol=currency["code"],
                kind="crypto",
            )
            for currency in currencies
            if currency["code"] not in existing_codes
        ]
    )


# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ MIGRATION                                                                          │
# └────────────────────────────────────────────────────────────────────────────────────┘


class Migration(migrations.Migration):

    dependencies = [
        ("beutils_currency", "0002_create_fiat_currencies"),
    ]

    operations = [migrations.RunPython(create_crypto_currencies)]
