# Generated by Django 3.1.1 on 2021-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beutils_currency", "0003_create_crypto_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=10),
        ),
    ]
